import './globals.scss';
import type { Metadata } from 'next';
import { NextAuthProvider, StoreProvider } from './providers';

export const metadata: Metadata = {
  title: 'EVIS Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <StoreProvider>{children}</StoreProvider>
      </NextAuthProvider>
    </html>
  );
}
